P_25_D feat: Усовершенствовал программу P_16_A так, чтобы ответы хранились в текстовом файле
Rulioff/Pascal pull request #10
Opened 2023-10-04 19:54 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/2428ea23-24c1-470f-8f8e-3abcea30cb50)

2023-10-04 20:14 UTC, dskrasnov requested changes

2023-10-04 20:14 UTC, dskrasnov commented on P_25_D.pas
> +    NumberLine := Random(6);
Почему 6?

2023-10-04 20:14 UTC, dskrasnov commented on P_25_D.pas
> +  function CountLines(var FileTxt: Text): integer;
Где используется эта функция?

2023-10-04 20:14 UTC, dskrasnov commented on Answer.txt
> +����� ��� �� ���� �������.
А ничего, что тут не отображаются символы? Локально все норм?

2023-10-05 06:36 UTC, Rulioff commented on P_25_D.pas
> +    NumberLine := Random(6);
Да надо было прокомментировать, что это значение зависит от числа строк в текстовом файле Answer.txt.

2023-10-05 06:46 UTC, Rulioff commented on Answer.txt
> +����� ��� �� ���� �������.
Локально кириллица отображается норм. Снова проблемы с кодировкой наверное.

2023-10-05 06:56 UTC, Rulioff commented on P_25_D.pas
> +  function CountLines(var FileTxt: Text): integer;
Недоглядел вчера на радостях. Посмотри 27 строку закоммител. Пытался сначала реализовать через подсчёт строк, потом переделал, а функцию забыл выпилить.

2023-10-05 06:57 UTC, dskrasnov commented on P_25_D.pas
> +    NumberLine := Random(6);
Это плохо. А если добавить или удалить строки в файле ответов? Придется править и перекомпилировать программу? При том, что в программе есть функция подсчета строк в файле, которая почему-то не используется.

2023-10-05 06:57 UTC, Rulioff commented on Answer.txt
> +����� ��� �� ���� �������.
Может на будущее вообще всё писать латиницей, чтобы не было непоняток?

2023-10-05 07:03 UTC, dskrasnov commented on Answer.txt
> +����� ��� �� ���� �������.
Не, нормально пока. Вот если надо будет понимать смысл, тогда латиницей.

2023-10-05 19:11 UTC, dskrasnov requested changes

2023-10-05 19:11 UTC, dskrasnov commented on P_25_D.pas
> +    AnswerOutput(FileInput, NumberLine);
А зачем в эту процедуру передается второй параметр? Что такое NumberLine и где ему присваивается значение?

2023-10-06 07:19 UTC, Rulioff commented on P_25_D.pas
> +    NumberLine := Random(6);
Была такая мысль и потерялась. Буду тренировать концентрацию.

2023-10-06 07:19 UTC, Rulioff commented on P_25_D.pas
> +    AnswerOutput(FileInput, NumberLine);
Второй параметр для определения текущей строки в тексте.
NumberLine - случайным образом выбранный номер строки текста, значение присвоено в 44 строке.

2023-10-06 07:19 UTC, Rulioff commented on P_25_D.pas
> +    AnswerOutput(FileInput, NumberLine);
Второй параметр для определения текущей строки в тексте.
NumberLine - случайным образом выбранный номер строки текста, значение присвоено в 44 строке.

2023-10-07 15:24 UTC, dskrasnov approved these changes

2023-10-07 15:27 UTC, merged