P_25_E feat: Программа показывает работу функции подсчета строк в файле Example_25_E.txt (не работает)
Rulioff/Pascal pull request #11
Opened 2023-10-16 17:18 UTC by Rulioff

2023-10-16 18:21 UTC, dskrasnov requested changes

2023-10-16 18:21 UTC, dskrasnov commented on P_25_E.pas
Не соответствует формулировке: "Выкати спева ПР с функцией подсчета строк в файле. Она должна принимать файловую переменную и возвращать кол-во строк. В основной программе должна быть демонстрация этой функции."

2023-10-16 20:18 UTC, Rulioff commented on P_25_E.pas
Исправил.

2023-10-17 11:37 UTC, dskrasnov requested changes

2023-10-17 11:37 UTC, dskrasnov commented on P_25_E.pas
> +    if Index = LastStringNumber then
А нужна ли эта проверка?

2023-10-17 12:41 UTC, Rulioff commented on P_25_E.pas
> +    if Index = LastStringNumber then
Проверка уже прошла в строке 43.

2023-10-17 18:01 UTC, dskrasnov approved these changes

2023-10-17 18:05 UTC, merged