P_26_V feat: Программа копирует содержимое файла в другой с перестановкой четных и нечетных строк и второй вариант решения с перестановкой строк в обратном порядке
Rulioff/Pascal pull request #14
Opened 2023-10-23 14:10 UTC by Rulioff

2023-10-23 15:05 UTC, dskrasnov requested changes

2023-10-23 15:05 UTC, dskrasnov commented on P_26_V.pas
> +  function CountLine(var FileTxt: Text): integer;
Давай уже нормальный нейминг сделаем.  Эта функция является приказом получить (get) количество (number) строк файла (file lines). Расставляем по правилам приближенным к англ. языку, но покороче т.е. родительный падеж без of, выкидываем артикли и т.п. GetFileLinesNumber

2023-10-23 15:05 UTC, dskrasnov commented on P_26_V.pas
> +  function LastString(var FileTxtOne: Text; LastStringNumber: integer): string;
И тут по аналогии. ПолучитьФайлаСтрокуПоНомеру Используй предлог By (бай).

2023-10-23 15:05 UTC, dskrasnov commented on P_26_V.pas
> +  StringNumber := 0;
А это нужно? Вроде результат этого присваивания нигде не используется.

2023-10-23 15:05 UTC, dskrasnov commented on P_26_V.pas
> +  while Count < StringNumber + 1 do
Выглядит как другой цикл. Нет?

2023-10-23 15:05 UTC, dskrasnov commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
Не пойдет. Сделай 2 программы - P_26_V_1.pas и P_26_V_2.pas И все будет понятно.

2023-10-23 15:05 UTC, dskrasnov commented on P_26_V.pas
> +    if Count mod 2 <> 0 then
А нужно ли это условие? Либо остаток от деления равен 0, либо неравен. Я не вижу других вариантов. Но я могу ошибиться.

2023-10-24 17:14 UTC, Rulioff commented on P_26_V.pas
> +  function CountLine(var FileTxt: Text): integer;
Исправил.

2023-10-24 17:15 UTC, Rulioff commented on P_26_V.pas
> +  function LastString(var FileTxtOne: Text; LastStringNumber: integer): string;
Использовал.

2023-10-24 17:16 UTC, Rulioff commented on P_26_V.pas
> +  StringNumber := 0;
Действительно, не используется.
Убрал.

2023-10-24 17:17 UTC, Rulioff commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
Сделал P_26_V_1.

2023-10-24 17:18 UTC, Rulioff commented on P_26_V.pas
> +    if Count mod 2 <> 0 then
Условие в 64 строке лишнее.

2023-10-24 18:25 UTC, Rulioff commented on P_26_V.pas
> +  while Count < StringNumber + 1 do
Заменил цикл в задаче P_26_V_2 на:
repeat
..
until.

2023-10-24 19:35 UTC, Rulioff commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
Сделал P_26_V_2.

2023-10-24 19:37 UTC, dskrasnov requested changes

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +  function GetFileLineByNumber(var FileTxtOne: Text; LastStringNumber: integer): string;
Ну, а нейминг в аргументах чего не поправил? Что значит FileTxtOne и LastStringNumber? Откуда One и Last? Почему String если в имени функции Line?

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +  function GetFileLinesNumber(var FileTxt: Text): integer;
Тут в аргументе ТекстовыйФайл т.е. TextFile.

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +    LastLine: string;
Last? Последняя? Лучше текущая.

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +  StringNumber, SendStringNumber: integer;
SendStringNumber звучит как название процедуры - ОтправитьСтрокиНомер. Неудачно.

Ну и определись - Стринг у тебя, или Лайн?

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +  StringNumber := GetFileLinesNumber(FileTxtFirst);
Получаешь LinesNumber, а хранишь его в StringNumber. Непорядок.

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +{P_26_V_1 Скопировать один файл в другой с перестановкой местами четных и нечетных строк.}
А ты уверен, что программа это делает?

2023-10-24 19:37 UTC, dskrasnov commented on p_26_v_1.pas
> +    FirstStringNumber: integer;
ПервойСтрокиНомер? Она же первая, Какой у нее еще может быть номер?

Или ПервыйСтрокиНомер? У нее много номеров? Зачем?

2023-10-24 19:47 UTC, dskrasnov commented on P_26_V.pas
> +  while Count < StringNumber + 1 do
Я пока вижу только p_26_v_1.pas если что. Но почему repeat? Ты не знаешь, сколько итераций потребуется и тебе нужна хотя бы одна чтобы выяснить это?

2023-10-24 19:48 UTC, dskrasnov commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
Я пока вижу только p_26_v_1.pas если что.

2023-10-25 07:01 UTC, Rulioff commented on P_26_V.pas
> +  while Count < StringNumber + 1 do
Задача P_26_V_2 в отдельной ветке:
https://github.com/Rulioff/Pascal/pull/15/commits/721b58801432faa34084bf5ae312d7ea706eb484

Число итераций известно, но в цикле for недопустим аргумент с условием.
![image](https://github.com/Rulioff/Pascal/assets/74359412/ccb85d89-3ca7-41a4-bfb3-c82d8f76ccba)

2023-10-25 07:03 UTC, Rulioff commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
P_26_V_2 в отдельной ветке, но буду ещё исправлять нейминг.
https://github.com/Rulioff/Pascal/pull/15/commits/721b58801432faa34084bf5ae312d7ea706eb484

2023-10-25 07:22 UTC, dskrasnov commented on P_26_V.pas
> +  while Count < StringNumber + 1 do
Лех, а нафига ты создал еще один ПР? У тебя в этом указано: "Программа копирует содержимое файла в другой с перестановкой четных и нечетных строк и второй вариант решения с перестановкой строк в обратном порядке". А ты создал новый ПР и начинаешь тут обсуждать то, что происходит там.

Прекращай безобразие. Переложи файлик сюда, тот ПР закрой без мержа, ненужную ветку удали.

2023-10-25 07:25 UTC, dskrasnov commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
Лех, а нафига ты создал еще один ПР? У тебя в этом указано: "Программа копирует содержимое файла в другой с перестановкой четных и нечетных строк и второй вариант решения с перестановкой строк в обратном порядке". А ты создал новый ПР и начинаешь тут обсуждать то, что происходит там.

Прекращай безобразие. Переложи файлик сюда, тот ПР закрой без мержа, ненужную ветку удали.

2023-10-25 19:53 UTC, Rulioff commented on P_26_V.pas
> +  while Count < StringNumber + 1 do
Исправил нейминг в задаче P_26_V_1.

2023-10-25 19:54 UTC, Rulioff commented on P_26_V.pas
> +Для первого решения программа готова к использованию, а для второго нужно
Исправил нейминг в задаче P_26_V_1.

2023-10-25 19:54 UTC, Rulioff commented on p_26_v_1.pas
> +  function GetFileLineByNumber(var FileTxtOne: Text; LastStringNumber: integer): string;
Исправил нейминг в задаче P_26_V_1.

2023-10-26 08:01 UTC, Rulioff commented on p_26_v_1.pas
> +{P_26_V_1 Скопировать один файл в другой с перестановкой местами четных и нечетных строк.}
Копирует не сам файл, а содержимое построчно с перестановкой.

2023-10-26 09:23 UTC, dskrasnov commented on p_26_v_1.pas
> +{P_26_V_1 Скопировать один файл в другой с перестановкой местами четных и нечетных строк.}
Ты  свой код читаешь хоть? Я читаю. Мне приходится.

2023-10-26 10:09 UTC, dskrasnov requested changes

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +  StringNumber := 0;
А это нужно? Вроде результат этого присваивания нигде не используется.

2023-10-26 10:09 UTC, dskrasnov commented on p_26_v_1.pas
> +  function GetFileLineByNumber(var SourceTxtFile: Text; LastLineTxt: integer): string;
Почему SourceTxtFile? Просто TextFile. Не усложняй.

Что такое LastLineTxt? ПоследнейЛинииТекст? Как это понимать?

2023-10-26 10:09 UTC, dskrasnov commented on p_26_v_1.pas
> +  function GetFileLinesNumber(var SourceTxtFile: Text): integer;
Тут в аргументе ТекстовыйФайл т.е. TextFile.

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +    LastLine: string;
Last? Последняя? Лучше текущая.

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +  StringNumber, RearrangingLine, SendStringNumber: integer;
SendStringNumber звучит как название процедуры - ОтправитьСтрокиНомер. Неудачно.

Ну и определись - Стринг у тебя, или Лайн?

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +  StringNumber := GetFileLinesNumber(FileTxtFirst);
Получаешь LinesNumber, а хранишь его в StringNumber. Непорядок.

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +    FirstStringNumber: integer;
ПервойСтрокиНомер? Она же первая, Какой у нее еще может быть номер?

Или ПервыйСтрокиНомер? У нее много номеров? Зачем?

2023-10-26 10:09 UTC, dskrasnov commented on p_26_v_1.pas
> +    LineNumberSource: integer;
Зачем Source? Тут есть еще какой-то номер строки и ты не хотел их путать?

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +· с перестановкой строк в обратном порядке (см. условие задачи «Е» к 25-й
Читай свой код! Что делает эта программа?

2023-10-26 10:09 UTC, dskrasnov commented on P_26_V_2.pas
> +  FileTxtFirst, FileTxtAnother: Text;
Вот тут как раз можно  использовать слова Source и Target в сочетании с TextFile.

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +· с перестановкой строк в обратном порядке (см. условие задачи «Е» к 25-й
Это условие из задачи, что с ним не так?

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +  FileTxtFirst, FileTxtAnother: Text;
Исправил.

2023-10-26 17:46 UTC, Rulioff commented on p_26_v_1.pas
> +{P_26_V_1 Скопировать один файл в другой с перестановкой местами четных и нечетных строк.}
Конечно я постарался перепутать условия.

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +· с перестановкой строк в обратном порядке (см. условие задачи «Е» к 25-й
Прочитал таки условие.

2023-10-26 17:46 UTC, Rulioff commented on p_26_v_1.pas
> +  function GetFileLinesNumber(var SourceTxtFile: Text): integer;
Исправил.

2023-10-26 17:46 UTC, Rulioff commented on p_26_v_1.pas
> +    LineNumberSource: integer;
На начальном этапе да. Я в эту процедуру размещал запись в конечный файл, но так не сработало.

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +  StringNumber := 0;
Исправил.

2023-10-26 17:46 UTC, Rulioff commented on p_26_v_1.pas
> +  function GetFileLineByNumber(var SourceTxtFile: Text; LastLineTxt: integer): string;
Заменил на TxtFile и LastLineNumber.

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +    LastLine: string;
Исправил.

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +  StringNumber, RearrangingLine, SendStringNumber: integer;
Заменил на OutputLineNumber.
![image](https://github.com/Rulioff/Pascal/assets/74359412/38e90fb4-651c-4843-a06b-edcfc0d36c2d)

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +  StringNumber := GetFileLinesNumber(FileTxtFirst);
Переделал на SourceLineNumber.
![image](https://github.com/Rulioff/Pascal/assets/74359412/49fe41c2-0f30-4477-ba9b-7aa830ff12ca)

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +    FirstStringNumber: integer;
Просто LineNumber.
![image](https://github.com/Rulioff/Pascal/assets/74359412/83b2b915-a327-4939-8edc-626649d31880)

2023-10-26 17:46 UTC, Rulioff commented on P_26_V_2.pas
> +  StringNumber := 0;
Исправил.

2023-10-26 17:50 UTC, dskrasnov commented on P_26_V_2.pas
> +{P_26_V_2 Скопировать один файл в другой с перестановкой строк в обратном порядке (см. условие задачи «Е» к 25-й
Для примера....

2023-10-26 17:52 UTC, Rulioff commented on P_26_V_2.pas
> +{P_26_V_2 Скопировать один файл в другой с перестановкой строк в обратном порядке (см. условие задачи «Е» к 25-й
Для примера....

2023-10-26 17:54 UTC, Rulioff commented on P_26_V_2.pas
> +{P_26_V_2 Скопировать один файл в другой с перестановкой строк в обратном порядке (см. условие задачи «Е» к 25-й
Для примера....

2023-10-26 18:22 UTC, dskrasnov commented on p_26_v_1.pas
> +  function GetFileLinesNumber(var SourceTxtFile: Text): integer;
Буковку "е" потерял.

2023-10-26 18:39 UTC, dskrasnov commented on P_26_V_2.pas
> +  FileTxtFirst, FileTxtAnother: Text;
Давай либо Source и Target, либо Input и Output. А у тебя чуть того, чуть другого.

2023-10-26 19:33 UTC, Rulioff commented on p_26_v_1.pas
> +  function GetFileLinesNumber(var SourceTxtFile: Text): integer;
Вернул букву "e".
![image](https://github.com/Rulioff/Pascal/assets/74359412/8f40973f-02b9-4125-8704-af21eea5b552)

2023-10-26 19:49 UTC, Rulioff commented on P_26_V_2.pas
> +  FileTxtFirst, FileTxtAnother: Text;
Заменил Output на Target.
![image](https://github.com/Rulioff/Pascal/assets/74359412/713f842a-42f0-42e5-97fd-5c13f2f98a26)

2023-10-27 09:11 UTC, dskrasnov requested changes

2023-10-27 09:11 UTC, dskrasnov commented on P_26_V_2.pas
> +  SourceLineNumber, OutputLineNumber: integer;
А вот строчкой ниже глаза не опустить, да? Почему тут оставил Output?

2023-10-27 09:11 UTC, dskrasnov commented on P_26_V_2.pas
> +  function GetFileLineByNumber(var TextFile: Text; LastLineNumber: integer): string;
Почему LastLineNumber? Откуда Last? Просто LineNumber.

2023-10-27 09:11 UTC, dskrasnov commented on P_26_V_2.pas
> +
Давай по убираем пустые строки в функциях и процедурах между сигнатурой и первым блоком.

2023-10-27 09:11 UTC, dskrasnov commented on p_26_v_1.pas
> +  SourceLineNumber := 0;
И куда тебе этот 0 нужен?

2023-10-27 09:11 UTC, dskrasnov commented on p_26_v_1.pas
> +  function GetFileLineByNumber(var TextFile: Text; LastLineNumber: integer): string;
Почему LastLineNumber? Откуда Last? Просто LineNumber.

2023-10-27 09:11 UTC, dskrasnov commented on p_26_v_1.pas
> +      NewLineNumber := (RearrangingLine - 1)
А как оно у тебя работает, если RearrangingLine начинается с 0?

2023-10-27 10:03 UTC, dskrasnov commented on p_26_v_1.pas
> +  NewLineNumber := 1;
А эта 1 где используется?

2023-10-27 12:15 UTC, Rulioff commented on P_26_V_2.pas
> +  SourceLineNumber, OutputLineNumber: integer;
Заменил OutputLineNumber на TargetLineNumber.
![image](https://github.com/Rulioff/Pascal/assets/74359412/ee12ddcb-d012-41a4-9b6e-59a87816b40b)

2023-10-27 12:18 UTC, Rulioff commented on P_26_V_2.pas
> +  function GetFileLineByNumber(var TextFile: Text; LastLineNumber: integer): string;
Убрал Last.
![image](https://github.com/Rulioff/Pascal/assets/74359412/c953214b-ecdb-47e5-97b0-d48ed2ab56c7)

2023-10-27 12:21 UTC, Rulioff commented on P_26_V_2.pas
> +
Убрал пустые строки.
![image](https://github.com/Rulioff/Pascal/assets/74359412/6ac91bfc-5654-497b-940d-b04307a18df1)

2023-10-27 12:33 UTC, Rulioff commented on p_26_v_1.pas
> +  SourceLineNumber := 0;
Удалил объявление переменной, не используется.

2023-10-27 12:34 UTC, Rulioff commented on p_26_v_1.pas
> +  function GetFileLineByNumber(var TextFile: Text; LastLineNumber: integer): string;
Убрал Last.

2023-10-27 12:34 UTC, Rulioff commented on p_26_v_1.pas
> +      NewLineNumber := (RearrangingLine - 1)
Начал отсчёт строк с 1-й.

2023-10-27 12:44 UTC, Rulioff commented on p_26_v_1.pas
> +  NewLineNumber := 1;
Нигде не используется, убрал.

2023-10-28 15:38 UTC, dskrasnov approved these changes

2023-10-28 15:39 UTC, merged