P_26_G feat: Разбили текстовый файла на 2, в первом нечетные, а во втором чётные строки
Rulioff/Pascal pull request #16
Opened 2023-11-03 12:28 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/a6f3ee32-61a3-4691-a5e7-e736548a1cb6)

2023-11-03 13:22 UTC, dskrasnov requested changes

2023-11-03 13:22 UTC, dskrasnov commented on P_26_G.pas
> +  SourceTextFile, OddLinesSourceFile, EvenLinesSourceFile: Text;
Что-то одни сорсы тут. А куда все пишется-то?

2023-11-03 13:22 UTC, dskrasnov commented on P_26_G.pas
> +      (SourceLineNumber - 2)) then
Итак, тут ты берешь нечетные строки, кроме скольки последних?

2023-11-03 13:22 UTC, dskrasnov commented on P_26_G.pas
> +    else if (CurrentLineNumber mod 2 <> 0) and (CurrentLineNumber <=
А тут нечетные строки, кроме скольки последних?

2023-11-03 13:22 UTC, dskrasnov commented on P_26_G.pas
> +    else
Очень много else. Этот код прекрасно пишется без единого else, ну или с одним. Просто нужно четче понимать, что у тебя в if.

А сейчас у тебя куча else работает как заплатки, на случай если ты накосячишь в каких-то if.

2023-11-03 13:50 UTC, Rulioff commented on P_26_G.pas
> +  SourceTextFile, OddLinesSourceFile, EvenLinesSourceFile: Text;
Чётные и нечётные от исходного файла.

2023-11-03 13:51 UTC, Rulioff commented on P_26_G.pas
> +      (SourceLineNumber - 2)) then
Кроме 2х последних.

2023-11-03 13:53 UTC, Rulioff commented on P_26_G.pas
> +    else if (CurrentLineNumber mod 2 <> 0) and (CurrentLineNumber <=
Тоже кроме 2х последних.

2023-11-03 13:54 UTC, Rulioff commented on P_26_G.pas
> +    else
Даже не знаю, что тебе ответить.

2023-11-03 14:35 UTC, dskrasnov commented on P_26_G.pas
> +  SourceTextFile, OddLinesSourceFile, EvenLinesSourceFile: Text;
Погоди. Это ж файл? Файл. Значит OddLinesSourceFile это НечетныхСтрокИсходныйФайл. А какой же это ИсходныйФайл? Это ЦелевойФайл.

2023-11-03 14:42 UTC, dskrasnov commented on P_26_G.pas
> +      (SourceLineNumber - 2)) then
CurrentLineNumber < (SourceLineNumber - 2)

Давай представим, что SourceLineNumber =3

Что получается?

2023-11-03 14:45 UTC, dskrasnov commented on P_26_G.pas
> +    else if (CurrentLineNumber mod 2 <> 0) and (CurrentLineNumber <=
Т.е. это условие не отличается от условия выше? Зачем тогда ты написал их по-разному? Это шифровка в центр?

2023-11-03 14:52 UTC, dskrasnov commented on P_26_G.pas
> +    else
Ты думал, тут есть хоть одно замечание не требующее правки кода? Тут же красным написано "Changes requested".
![image](https://github.com/Rulioff/Pascal/assets/5615773/ef67110b-38fd-4206-a74d-83b809db5264)

2023-11-03 17:24 UTC, Rulioff commented on P_26_G.pas
> +      (SourceLineNumber - 2)) then
Получим, что не напечатается ни одной строки. 0<1.

2023-11-04 13:30 UTC, Rulioff commented on P_26_G.pas
> +  SourceTextFile, OddLinesSourceFile, EvenLinesSourceFile: Text;
Исправил на OddLinesTargetFile и EvenLinesTargetFile.

2023-11-04 13:31 UTC, Rulioff commented on P_26_G.pas
> +    else if (CurrentLineNumber mod 2 <> 0) and (CurrentLineNumber <=
Исправил шифровку.

2023-11-04 13:32 UTC, Rulioff commented on P_26_G.pas
> +    else
Убрал все Else.

2023-11-04 15:20 UTC, dskrasnov approved these changes

2023-11-04 15:21 UTC, merged