P_27_V feat: Создали программу, печатающую из файла строки, в которых скобки расставлены неверно
Rulioff/Pascal pull request #18
Opened 2023-11-09 18:14 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/19611481-bcbb-410f-9f86-2f8582b87b1d)

2023-11-09 21:00 UTC, dskrasnov commented on P_27_V.pas
> +  function Check(Line: string): boolean;
А что-то кроме True эта функция выдает?

2023-11-09 21:01 UTC, dskrasnov commented on P_27_V.pas
> +    if Check(Line) = False then
У тебя булева функция. Зачем сравнение?

2023-11-09 21:05 UTC, dskrasnov commented on P_27_V.pas
> +  function Check(Line: string): boolean;
А что-то кроме True эта функция выдает?

2023-11-09 21:05 UTC, dskrasnov commented on P_27_V.pas
> +    if Check(Line) = False then
У тебя булева функция. Зачем сравнение?

2023-11-09 21:07 UTC, dskrasnov requested changes

2023-11-09 21:07 UTC, dskrasnov commented on P_27_V.pas
> +  function Check(Line: string): boolean;
А что-то кроме True эта функция выдает?

2023-11-09 21:07 UTC, dskrasnov commented on P_27_V.pas
> +    if Check(Line) = False then
У тебя булева функция. Зачем сравнение?

2023-11-10 15:32 UTC, Rulioff commented on P_27_V.pas
> +  function Check(Line: string): boolean;
Ничего.

2023-11-10 17:29 UTC, Rulioff commented on P_27_V.pas
> +    if Check(Line) = False then
Исправил.

2023-11-10 17:40 UTC, dskrasnov approved these changes

2023-11-10 17:49 UTC, merged