P_24_A Задача верно шифрует и дешифрует латинские символы при ключе от 1 до 25
Rulioff/Pascal pull request #2
Opened 2023-09-18 17:15 UTC by Rulioff

Условие выполнено, можно мёрджить?

2023-09-18 18:19 UTC, dskrasnov commented
В описании коммита надо указывать, что сделано, а не что надо сделать. Исправь.
![image](https://github.com/Rulioff/Pascal/assets/5615773/c7a03b0e-0990-4cd9-940c-ee082cf04cae)

2023-09-18 18:36 UTC, dskrasnov requested changes

2023-09-18 18:36 UTC, dskrasnov commented on P_24_A.pas
> +    Readln(Key);
```suggestion
    Readln(Key);

```

2023-09-18 18:36 UTC, dskrasnov commented on P_24_A.pas
> +    Readln(Line);
```suggestion
    Readln(Line);

```

2023-09-18 18:36 UTC, dskrasnov commented on P_24_A.pas
> +    Readln(Operation);
```suggestion
    Readln(Operation);

```

2023-09-18 18:36 UTC, dskrasnov commented on P_24_A.pas
> +    Readln(Operation);
Это я к тому, что хорошо бы каждую пару врайт-рид отбить пустой строкой. Можешь прям тут попринимать мои предложения и не париться локально.

2023-09-19 16:40 UTC, Rulioff commented
Мне нужно сейчас исправлять описание коммитов или это просто совет на будущее?

2023-09-19 18:41 UTC, dskrasnov approved these changes

2023-09-19 18:44 UTC, merged