P_30_A feat: Функция FractionalPartNumber выделяет дробную часть вещественного числа
Rulioff/Pascal pull request #21
Opened 2023-11-19 17:35 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/2b52ab38-2df1-4159-a833-9d77a46a7cef)

2023-11-19 17:58 UTC, dskrasnov requested changes

2023-11-19 17:58 UTC, dskrasnov commented on P_30_A.pas
> +  function FractionalPartNumber(Number: real): real;
Переименуй функцию в GetNumberFractionalPart

2023-11-19 18:37 UTC, Rulioff commented on P_30_A.pas
> +  function FractionalPartNumber(Number: real): real;
Переименовал.

2023-11-19 18:53 UTC, dskrasnov requested changes

2023-11-19 18:53 UTC, dskrasnov commented on P_30_A.pas
> +    WriteLn('Остаток от числа = ', GetNumberFractionalPart(Number): 10: 6);
Не "Остаток от числа", а  "Дробная часть"

2023-11-19 18:53 UTC, dskrasnov commented on P_30_A.pas
> +    Write('Введите вещественное число, чтобы получить остаток, для выхода 0: ');
Не "остаток", а "дробную часть"

2023-11-19 20:16 UTC, Rulioff commented on P_30_A.pas
> +    WriteLn('Остаток от числа = ', GetNumberFractionalPart(Number): 10: 6);
Исправил.

2023-11-19 20:16 UTC, Rulioff commented on P_30_A.pas
> +    Write('Введите вещественное число, чтобы получить остаток, для выхода 0: ');
Исправил.

2023-11-20 07:08 UTC, dskrasnov approved these changes

2023-11-20 07:23 UTC, merged