P_30_V feat: В файл Numbers_P_30.txt, сохраняем 100 случайных чисел от 0 до 999, определяем: 1) максимальное и минимальное число; 2) сумму всех чисел; 3) среднее арифметическое и выводим результат
Rulioff/Pascal pull request #22
Opened 2023-11-21 14:02 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/4bdce58d-256c-4038-b8db-c4887f5adb0c)

2023-11-21 15:47 UTC, dskrasnov requested changes

2023-11-21 15:47 UTC, dskrasnov commented on P_30_V.pas
> +  Number, Index, Choice: integer;
У тебя есть глобальные Number и Index...

2023-11-21 15:47 UTC, dskrasnov commented on P_30_V.pas
> +      Read(Numbers, Number);
....тут ты используешь глобальный Number...

2023-11-21 15:47 UTC, dskrasnov commented on P_30_V.pas
> +      Read(Numbers, Number);
...и тут...

2023-11-21 15:47 UTC, dskrasnov commented on P_30_V.pas
> +      Read(Numbers, Number);
...и тут...

2023-11-21 15:47 UTC, dskrasnov commented on P_30_V.pas
> +      Read(Numbers, Number);
...и тут...

2023-11-21 15:47 UTC, dskrasnov commented on P_30_V.pas
> +    Index: integer;
...и внезапно, только в этой функции ты используешь локальный Index.

В чем логика? Почему везде один глобальный Number, а тут локальный Index? Это осознанное решение? Ты не боишься перестать понимать, что лежит в Number на каждом шаге программы?

2023-11-21 16:05 UTC, dskrasnov commented on P_30_V.pas
> +    Write('Введите 1 для определения минимального и максимального числа, 2 для суммы или 3 для среднеарифметического и 0 для выхода: ');
Красиво, конечно. Но требовала ли этого задача? По условию, надо вычислить все три показателя. И по хорошему, это надо делать не отдельными функциями т.к. тогда один и тот же файл будет читаться трижды.

2023-11-22 11:01 UTC, Rulioff commented on P_30_V.pas
> +  Number, Index, Choice: integer;
Убрал функции.

2023-11-22 11:01 UTC, Rulioff commented on P_30_V.pas
> +      Read(Numbers, Number);
Убрал функции.

2023-11-22 11:02 UTC, Rulioff commented on P_30_V.pas
> +      Read(Numbers, Number);
Number только глобальная.

2023-11-22 11:02 UTC, Rulioff commented on P_30_V.pas
> +      Read(Numbers, Number);
Number только глобальная.

2023-11-22 11:02 UTC, Rulioff commented on P_30_V.pas
> +      Read(Numbers, Number);
Number только глобальная.

2023-11-22 11:03 UTC, Rulioff commented on P_30_V.pas
> +    Index: integer;
Убрал функции.

2023-11-22 11:04 UTC, Rulioff commented on P_30_V.pas
> +    Write('Введите 1 для определения минимального и максимального числа, 2 для суммы или 3 для среднеарифметического и 0 для выхода: ');
Убрал функции.

2023-11-22 13:19 UTC, dskrasnov requested changes

2023-11-22 13:19 UTC, dskrasnov commented on P_30_V.pas
> +  begin
А этот begin зачем?

2023-11-22 13:19 UTC, dskrasnov commented on P_30_V.pas
> +  Number := 0;
Это для чего?

2023-11-22 13:19 UTC, dskrasnov commented on P_30_V.pas
> +    Write(Numbers, Number, ' ');
Тут промежуточная переменная Number  не нужна.

2023-11-22 13:19 UTC, dskrasnov commented on P_30_V.pas
> +  CountNumber = 100;
CountNumber? Что это и какой логикой объясняется такое имя? MaxNumber и MinNumber понимаю - максимальное и минимальное число. А CountNumber это какое число?

2023-11-23 13:11 UTC, Rulioff commented on P_30_V.pas
> +  begin
Он лишний.

2023-11-23 13:15 UTC, Rulioff commented on P_30_V.pas
> +  Number := 0;
Тут начинается основной программный блок.

2023-11-23 13:26 UTC, Rulioff commented on P_30_V.pas
> +    Write(Numbers, Number, ' ');
Без промежуточной переменной мы в текстовый файл запишем ничего.

2023-11-23 13:39 UTC, dskrasnov commented on P_30_V.pas
> +  Number := 0;
Для чего ты обнуляешь Number? Где используется этот ноль?

2023-11-23 13:45 UTC, dskrasnov commented on P_30_V.pas
> +    Write(Numbers, Number, ' ');
Чего? Почему?

Write(Numbers, Random(UpperBound), ' ');

Как это приведет к записи ничего?

2023-11-23 13:51 UTC, Rulioff commented on P_30_V.pas
> +  CountNumber = 100;
CountNumber, это количество чисел в файле. А UpperBound верхняя граница чисел, так назвал константу, чтобы не путать с переменной MaxNumber.

2023-11-23 14:07 UTC, Rulioff commented on P_30_V.pas
> +  Number := 0;
Убрал.

2023-11-23 14:08 UTC, Rulioff commented on P_30_V.pas
> +    Write(Numbers, Number, ' ');
Сразу не сообразил.
Всё исправил.

2023-11-23 14:16 UTC, dskrasnov commented on P_30_V.pas
> +  CountNumber = 100;
Если это количество чисел, то последним словом должно быть количество. Вспоминай правила образования родительного падежа в английском языке. Ты раз за разом совершаешь эту ошибку.

2023-11-24 10:15 UTC, Rulioff commented on P_30_V.pas
> +  CountNumber = 100;
Переделал в родительный падеж. Исправил остальные бяки. И запушил.

2023-11-24 11:07 UTC, dskrasnov requested changes

2023-11-24 11:07 UTC, dskrasnov commented on P_30_V.pas
> +    AmountNumbers := AmountNumbers + Number;
AmountNumbers ? Давай разберем:

1. Окончание s т.е. это массив.
2. Последнее слово Number т.е. речь идет о числе.
3. Слово Amount (сумма) перед Number т.е. оно описывает это число. Какое оно? Суммированное?

Т.е. речь идет о массиве суммированных чисел? Ты это хотел сказать?

2023-11-24 17:41 UTC, Rulioff commented on P_30_V.pas
> +    AmountNumbers := AmountNumbers + Number;
Заменил на ArraySummedNumbers.

2023-11-24 18:34 UTC, dskrasnov commented on P_30_V.pas
> +    AmountNumbers := AmountNumbers + Number;
Не годится.  Или поясни, как это должно звучать на русском.

2023-11-24 18:56 UTC, Rulioff commented on P_30_V.pas
> +    AmountNumbers := AmountNumbers + Number;
Исправил на Amount.

2023-11-24 19:00 UTC, dskrasnov approved these changes

2023-11-24 20:14 UTC, merged