P_33_B feat: Процедура принимает строку, вычисляет среднеарифметическое кодов её символов и печатает его с двумя цифрами после точки
Rulioff/Pascal pull request #30
Opened 2023-12-07 13:19 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/224d1302-ae16-42d1-8f12-1103f8df3a3b)

2023-12-07 14:07 UTC, dskrasnov requested changes

2023-12-07 14:07 UTC, dskrasnov commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
PrinttSymbolsCodesArithmeticMean

Исправь и предположи, почему именно так.

2023-12-07 14:07 UTC, dskrasnov commented on P_33_B.pas
> +      Symbol := Line[Index];
Symbol не нужен.

2023-12-07 14:07 UTC, dskrasnov commented on P_33_B.pas
> +      Code := Ord(Symbol);
Code не нужен.

2023-12-07 14:07 UTC, dskrasnov commented on P_33_B.pas
> +      Sum := Sum + Code;
Это несложное действие можно записать одной строкой. А ты расписываешь, будто тебе за строчки платят.

Читабельность нужна там, где есть что читать. :-)

2023-12-08 06:43 UTC, Rulioff commented on P_33_B.pas
> +      Sum := Sum + Code;
Это вариант без лишних переменных, в одну строку. Что не так?
![image](https://github.com/Rulioff/Pascal/assets/74359412/150df807-65d3-430a-8ad8-0122be9b9091)

2023-12-08 06:46 UTC, Rulioff commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
Полагаю, Print потому что в условии чётко сказано: "печатает", а не считает возвращает результат.

2023-12-08 06:48 UTC, Rulioff commented on P_33_B.pas
> +      Symbol := Line[Index];
Считаю, что нужен.

2023-12-08 06:48 UTC, Rulioff commented on P_33_B.pas
> +      Code := Ord(Symbol);
А вот без него можно обойтись.

2023-12-08 07:01 UTC, dskrasnov commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
Я изменил порядок слов. Почему?

2023-12-08 07:06 UTC, dskrasnov commented on P_33_B.pas
> +      Sum := Sum + Code;
Еще раз повторяю вопрос:

А символы в строке нумеруются от 1?

2023-12-08 07:22 UTC, Rulioff commented on P_33_B.pas
> +      Sum := Sum + Code;
"В Паскале стандартный строковой тип (string) представляется в виде массива символов, индексация в котором начинается с 0".
Но в данной задаче по логике надо нумеровать с 1.

2023-12-08 07:28 UTC, Rulioff commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
Не могу знать.

2023-12-08 07:28 UTC, Rulioff commented on P_33_B.pas
> +      Symbol := Line[Index];
Убрал переменную Symbol.

2023-12-08 07:56 UTC, Rulioff commented on P_33_B.pas
> +      Code := Ord(Symbol);
Убрал переменную Code.

2023-12-08 10:07 UTC, dskrasnov commented on P_33_B.pas
> +      Sum := Sum + Code;
![image](https://github.com/Rulioff/Pascal/assets/5615773/2986a190-6d94-4d74-b1ad-26c84974c33f)

2023-12-08 10:09 UTC, dskrasnov commented on P_33_B.pas
> +      Sum := Sum + Code;
...и логика данной задачи тут не при чем.

2023-12-08 10:16 UTC, dskrasnov commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
Ну, ты подумай. Я около недели назад все разжевал. Попробуй таки обсудить это со Светой. Если не справитесь, надиктую - законспектируешь. У меня мам так комп осваивала - с тетрадочкой. :-)

2023-12-08 10:43 UTC, Rulioff commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
Родительный падеж пишем среднеарифметическое of кодов символов, а если убираем of, то меняем местами последние слова?

2023-12-08 10:44 UTC, Rulioff commented on P_33_B.pas
> +      Sum := Sum + Code;
Ясно.

2023-12-08 10:54 UTC, dskrasnov commented on P_33_B.pas
> +  procedure CalculationArithmeticMeanCodesSymbols(Line: string);
Все верно.

2023-12-08 10:56 UTC, dskrasnov approved these changes

2023-12-08 11:13 UTC, merged