P_33_V feat: Печатаем 20 случайных вещественных чисел от 0 до 10 с 3-мя знаками после точки
Rulioff/Pascal pull request #31
Opened 2023-12-11 12:25 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/e6cd7aea-e509-4300-94af-50f096d3a84c)

2023-12-11 12:58 UTC, dskrasnov requested changes

2023-12-11 12:58 UTC, dskrasnov commented on P_33_V.pas
> +  NumbersCount = 20;
Это зачем?

2023-12-11 12:58 UTC, dskrasnov commented on P_33_V.pas
> +  Index: longint;
Почему longint?

2023-12-11 12:58 UTC, dskrasnov commented on P_33_V.pas
> +    Write(Random(10000) / 1000: 15: 3);
Почему 15? От алды и с запасом? Оптимизируй.

2023-12-11 13:04 UTC, Rulioff commented on P_33_V.pas
> +  NumbersCount = 20;
Чтобы проще было менять количество чисел по условию задачи.

2023-12-11 13:05 UTC, Rulioff commented on P_33_V.pas
> +  Index: longint;
Компилятор ругается на integer.

2023-12-11 13:11 UTC, Rulioff commented on P_33_V.pas
> +    Write(Random(10000) / 1000: 15: 3);
2 знака до запятой и 3 после, отступ 10.

2023-12-11 13:23 UTC, Rulioff commented on P_33_V.pas
> +    Write(Random(10000) / 1000: 15: 3);
Оптимизировал.

2023-12-11 13:25 UTC, dskrasnov commented on P_33_V.pas
> +  NumbersCount = 20;
А задача это требует?

2023-12-11 13:27 UTC, dskrasnov commented on P_33_V.pas
> +  Index: longint;
Реально? Вообще, тут байта хватит.

2023-12-11 13:34 UTC, Rulioff commented on P_33_V.pas
> +  NumbersCount = 20;
Нет.

2023-12-11 13:36 UTC, Rulioff commented on P_33_V.pas
> +  NumbersCount = 20;
Убрал.

2023-12-11 13:39 UTC, Rulioff commented on P_33_V.pas
> +  Index: longint;
![image](https://github.com/Rulioff/Pascal/assets/74359412/725e579d-f3a6-4ee5-ac5d-4fd68a91f308)

2023-12-11 13:41 UTC, Rulioff commented on P_33_V.pas
> +  Index: longint;
Шутка)

2023-12-11 13:42 UTC, Rulioff commented on P_33_V.pas
> +  Index: longint;
Сделал байт.

2023-12-11 14:17 UTC, dskrasnov approved these changes

2023-12-11 14:17 UTC, dskrasnov commented on P_33_V.pas
> +    Write(Random(10000) / 1000: NumbersCount: 3);
Что это ты тут сделал? Поясни.

2023-12-12 08:38 UTC, Rulioff commented on P_33_V.pas
> +    Write(Random(10000) / 1000: NumbersCount: 3);
Тут я сделал херь полную, за отступ взял константу количества чисел, значит разрыв будет 50 символов, если возьмём 50 чисел. Исправил, как ты сказал.

2023-12-12 08:57 UTC, merged