P_34_D feat: Функция ввода целого числа, принимает строку-приглашение и возвращает введенное число
Rulioff/Pascal pull request #39
Opened 2023-12-22 14:57 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/1ac71e12-c86b-43f3-897d-96ff038cc68e)

2023-12-22 22:03 UTC, dskrasnov requested changes

2023-12-22 22:03 UTC, dskrasnov commented on P_34_D.pas
> +    Price: integer;
Функция ввода целого числа. Почему Price?

2023-12-22 22:03 UTC, dskrasnov commented on P_34_D.pas
> +    GetNumber(' потратили '), ' руб.', GetNumber(' и '), ' коп.');
Как оно работает-то, вообще? Если я не ошибаюсь, то должно быть так:

1. Печатает ' потратили '.
2. Ожидает ввода.
3. Печатает ' и '.
4. Ожидает ввода.
5. Печатает 'Введите стоимость покупки, пожалуйста:  ЧИСЛО руб.' ЧИСЛО коп.'.

Если все так, то это криво.

2023-12-23 06:34 UTC, Rulioff commented on P_34_D.pas
> +    Price: integer;
Потому что в примере нужно ввести стоимость покупки.

2023-12-23 06:42 UTC, Rulioff commented on P_34_D.pas
> +    GetNumber(' потратили '), ' руб.', GetNumber(' и '), ' коп.');
Нет, немного другая последовательность:
![image](https://github.com/Rulioff/Pascal/assets/74359412/c788d037-f0ea-4a51-bfae-d3a017df6735)

2023-12-23 08:38 UTC, dskrasnov commented on P_34_D.pas
> +    GetNumber(' потратили '), ' руб.', GetNumber(' и '), ' коп.');
Все равно криво, но не буду придираться. Лучше обсудить.

2023-12-23 08:52 UTC, dskrasnov requested changes

2023-12-23 08:52 UTC, dskrasnov commented on P_34_D.pas
> +    Price: integer;
Еще раз. Функция ввода целого числа. Она принимает строку-приглашение и возвращает введенное число. Она называется GetNumber. Она не знает и не должна ничего знать о том, где и как она используется. Сегодня ты ее используешь для ввода стоимости, а завтра для ввода длинны. И что? Каждый раз будешь переименовывать переменную?

Исправь.

2023-12-23 15:54 UTC, dskrasnov approved these changes

2024-01-10 16:33 UTC, merged