P_24_G feat: Решил задачу вывести позиции всех символов, кроме пробелов, по порядку
Rulioff/Pascal pull request #4
Opened 2023-09-21 18:12 UTC by Rulioff

P_24_G Для введённой пользователем строки напечатать позиции всех
встречающихся в ней символов, кроме пробелов, в порядке их следования в строке.
Например, для слова «PASCAL»
P – 1
A – 2 5
S – 3
C – 4
L – 6

2023-09-21 19:10 UTC, dskrasnov requested changes

2023-09-21 19:10 UTC, dskrasnov commented on P_24_G.pas
> +  Index, Position: integer;
По сути -  они оба индексы. Пусть один будет полный, а другой частичный. FullIndex и PartialIndex.

2023-09-22 06:46 UTC, Rulioff commented on P_24_G.pas
> +  Index, Position: integer;
Интересный ход, я над этим вчера долго думал, и остался недоволен.

2023-09-22 18:15 UTC, dskrasnov approved these changes

2023-09-23 13:58 UTC, merged