P_37_A feat: Написал процедуры ввода и вывода множества символов
Rulioff/Pascal pull request #42
Opened 2024-01-19 17:27 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/88ea2ca2-1537-4910-9700-4be6d081273a)

2024-01-19 17:43 UTC, dskrasnov requested changes

2024-01-19 17:43 UTC, dskrasnov commented on P_37_A.pas
> +    ReadLn(ArgumentFile);
А что делает эта строчка?

2024-01-19 17:43 UTC, dskrasnov commented on P_37_A.pas
> +    WriteLn(ArgumentFile);
А что делает эта строчка?

2024-01-19 17:43 UTC, dskrasnov commented on P_37_A.pas
> +  ReadLn;
А где демонстрация написанных процедур? Они работают вообще?

2024-01-20 07:17 UTC, Rulioff commented on P_37_A.pas
> +    ReadLn(ArgumentFile);
№24 - перевод по окончании строки.

2024-01-20 07:17 UTC, Rulioff commented on P_37_A.pas
> +    WriteLn(ArgumentFile);
№34 - по окончании переход на следующую строку.

2024-01-20 08:01 UTC, Rulioff commented on P_37_A.pas
> +  ReadLn;
По условию не требуется программа для проверки. Работают обе процедуры, проверил.

2024-01-20 15:15 UTC, Rulioff commented on P_37_A.pas
> +  ReadLn;
![image](https://github.com/Rulioff/Pascal/assets/74359412/fa2c923b-0088-4eda-9203-1c5b873b8b3d)

2024-01-20 15:20 UTC, Rulioff commented on P_37_A.pas
> +    ReadLn(ArgumentFile);
Строки 24 и 34 нужны если чтение из файла, а если ввод с клавиатуры, то они не нужны.

2024-01-21 12:35 UTC, dskrasnov approved these changes

2024-01-21 12:36 UTC, merged