P_37_B feat: Написал функцию, принимающую числовое множество и возвращающую количество содержащихся в нём элементов
Rulioff/Pascal pull request #43
Opened 2024-02-05 12:48 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/a326eace-57d0-4201-b78f-c1710a79b417)

2024-02-05 18:00 UTC, dskrasnov requested changes

2024-02-05 18:00 UTC, dskrasnov commented on P_37_B.pas
> +возвращающую количество содержащихся в нём элементов. }
В моем понимании, тут должна быть функция, которая принимает множество и возвращает мощность. А у тебя функция принимает файл и множество, а возвращает количество уникальных чисел в файле. Это самодеятельность.

2024-02-05 18:00 UTC, dskrasnov commented on P_37_B.pas
> +  function SetsPower(var ArgumentFile: Text; var ArgumentSet: TypeSet): byte;
Первое слово в имени функции, которая позволяет что-то получить, должно быть Get.

И почему Sets? Там много множеств?

И не Power, а Cardinality. Тогда Sets можно вообще опустить.

2024-02-05 18:00 UTC, dskrasnov commented on P_37_B.pas
> +  Assign(InputFile, 'Input_P_37.in');
Нафиг тут файл? Просто создай множество руками и выясни его мощность.

2024-02-06 12:11 UTC, Rulioff commented on P_37_B.pas
> +  function SetsPower(var ArgumentFile: Text; var ArgumentSet: TypeSet): byte;
Это родительный падеж, мощность одного множества.

2024-02-07 07:20 UTC, dskrasnov commented on P_37_B.pas
> +  function SetsPower(var ArgumentFile: Text; var ArgumentSet: TypeSet): byte;
Мы договорились опускать апостроф и "s" из родительного падежа. Это нужно для того чтобы не возникало такой вот путаницы с множественным числом. Ну и для дополнительного сокращения.

Но тут лучше использовать Cardinality без Set т.к. Set это общепринятый префикс имени функции, которая что-то устанавливает. Таким образом, SetPower можно прочесть как УстановитьМощность. Лучше не допускать таких неоднозначных имен.

2024-03-22 14:50 UTC, dskrasnov requested changes

2024-03-22 14:50 UTC, dskrasnov commented on P_37_B.pas
> +  until (Number in [256]);
Почему не until (Number = 256); ?

2024-03-22 14:50 UTC, dskrasnov commented on P_37_B.pas
> +  Number: byte;
Почему byte? А если надо integer, какие правки потребуются?

2024-03-22 14:50 UTC, dskrasnov commented on P_37_B.pas
> +  Numbers: TypeCardinality;
А зачем TypeCardinality? Нельзя сразу сделать так: Numbers: set of 0..255;?

2024-03-22 14:50 UTC, dskrasnov commented on P_37_B.pas
> +  TypeCardinality = set of 0..255;
А 0..255 это о чем говорит?

2024-03-22 16:53 UTC, Rulioff commented on P_37_B.pas
> +  TypeCardinality = set of 0..255;
Надо исправить на 1..255

2024-03-22 16:55 UTC, Rulioff commented on P_37_B.pas
> +  Number: byte;
Нельзя, TypeCardinality использую в 18 строке, как тип аргумента функции.

2024-03-22 17:08 UTC, Rulioff commented on P_37_B.pas
> +  until (Number in [256]);
Потому что так не работает. Нужно указывать элемент множества, а не число или символ.

2024-03-22 17:36 UTC, dskrasnov commented on P_37_B.pas
> +  until (Number in [256]);
Не, погоди. Ты вводишь обычное число. В множество ты его кладешь или нет - какая разница. У тебя должна быть  возможность сделать Number = 256 или даже Number > 255.

2024-03-22 17:37 UTC, dskrasnov commented on P_37_B.pas
> +  Number: byte;
Я про byte спрашиваю.

2024-03-22 17:40 UTC, dskrasnov commented on P_37_B.pas
> +  TypeCardinality = set of 0..255;
Я про смысл спрашиваю. Я не изучал множества и не понимаю, что это значит.

Ладно, устно расскажешь.  Не парься.

2024-03-23 07:22 UTC, Rulioff commented on P_37_B.pas
> +  Numbers: TypeCardinality;
Нельзя, TypeCardinality использую в 18 строке, как тип аргумента функции.

2024-03-24 12:24 UTC, dskrasnov approved these changes

2024-03-24 12:26 UTC, merged