P_38_B feat: Сформировал 3 множества по классам и 4 по цвету автомобилей, определил кол-во авто, нашёл кол-во и номера автомобилей разрешённых для въезда
Rulioff/Pascal pull request #47
Opened 2024-04-21 14:00 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/f6f99a3a-f419-45c5-bd67-10bbb7e50155)
![image](https://github.com/Rulioff/Pascal/assets/74359412/624fdf17-9603-4e7e-87ec-183a61a780b4)

2024-04-21 20:23 UTC, dskrasnov requested changes

2024-04-21 20:23 UTC, dskrasnov commented on P_38_B.pas
> +    if Index mod (5) = 0 then
Если ты поместил номер в Buses, зачем потом пытаться запихивать его куда-то еще? Он уже автобус, он не может быть грузовиком. Вспомни процедуру continue.

2024-04-21 20:23 UTC, dskrasnov commented on P_38_B.pas
> +    if Index mod (7) = 0 then
А зачем скобки вокруг числа? Можно вообще без скобок же. Ну если очень надо скобку, то вот так:
`if (Index mod 7) = 0 then`

2024-04-21 20:23 UTC, dskrasnov commented on P_38_B.pas
> +    if (Index mod (7) = 0) and (Index mod (5) = 0) then
Эта проверка не нужна, если ты перестанешь пихать автобусы в грузовики. Вспомни процедуру continue.

2024-04-21 20:23 UTC, dskrasnov commented on P_38_B.pas
> +    if Index mod (4) = 0 then
Типы машин обработай в одном цикле, а цвета в другом. Не мешай цветам и типам накладываться друг на друга. У каждой машины есть и тип и цвет. Не забывай процедуру continue.

2024-04-22 16:50 UTC, Rulioff commented on P_38_B.pas
> +    if Index mod (7) = 0 then
Совсем убрал скобки.

2024-04-22 16:52 UTC, Rulioff commented on P_38_B.pas
> +    if (Index mod (7) = 0) and (Index mod (5) = 0) then
Да. Процедура Continue убирает 76 строку.

2024-04-22 16:54 UTC, Rulioff commented on P_38_B.pas
> +    if Index mod (4) = 0 then
Спасибо! Сам бы не додумался использовать процедуру Continue. Теперь всё работает.

2024-04-22 17:17 UTC, dskrasnov approved these changes

2024-04-22 17:37 UTC, merged