P_38_G feat: Программа для генерации пароля длиной не менее восьми символов, 4 разных пароля соответствующие условиям
Rulioff/Pascal pull request #49
Opened 2024-05-11 16:31 UTC by Rulioff

![Uploading image.png…]()

2024-05-13 08:17 UTC, dskrasnov requested changes

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +  AllSymbols := '';
Зачем эти присвоения? Эти пустые строки успевают на что-то повлиять?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +  FirstPassword := '';
А это тут зачем?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +  function GetNumbersLine(): string;
Во-первых, не line, а string. Во-вторых, указывать на тип в имени - дурной тон. В объявлении уже указаны все типы. Масло масляное получается. Поэтому просто GetNumbers.

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +  function GetCharsLine(): string;
Во-первых, не line, а string. Во-вторых, указывать на тип в имени - дурной тон. В объявлении уже указаны все типы. Масло масляное получается. Поэтому просто GetChars.

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +  function GetCapsCharsLine(): string;
Во-первых, не line, а string. Во-вторых, указывать на тип в имени - дурной тон. В объявлении уже указаны все типы. Масло масляное получается. Поэтому просто GetCapsChars.

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +  AllSymbols, FourthPassword, SecondPassword, ThirdPassword, FirstPassword: string;
А почему FourthPassword, SecondPassword, ThirdPassword, FirstPassword в глобальных переменных? Они нужны в основной программе?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +    while Length(FirstPassword) < 8 + Random(3) do
Т.е. ты при каждой проверке в цикле генеришь новое случайное число? Зачем?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +    while Length(SecondPassword) < 8 + Random(3) do
Т.е. ты при каждой проверке в цикле генеришь новое случайное число? Зачем?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +    while Length(ThirdPassword) < 8 + Random(3) do
Т.е. ты при каждой проверке в цикле генеришь новое случайное число? Зачем?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +      Result := FirstPassword;
Не понял. У тебя функция отдает значение внутри цикла? И сколько значений она сможет отдать? Это какое-то новое слово в Паскале?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Т.е. у тебя тут длинна пароля будет строго кратна 3. Это не правильно.

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +      Result := ThirdPassword;
Не понял. У тебя функция отдает значение внутри цикла? И сколько значений она сможет отдать? Это какое-то новое слово в Паскале?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Т.е. у тебя тут длинна пароля будет строго кратна 3. Это не правильно.

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +      Result := FourthPassword;
Не понял. У тебя функция отдает значение внутри цикла? И сколько значений она сможет отдать? Это какое-то новое слово в Паскале?

2024-05-13 08:17 UTC, dskrasnov commented on P_38_G.pas
> +      end;
А что если,  на некотором шаге, UnicChar и UnicCapsChar сгенерились неуникальными? Твой алгоритм их выкинет и вернется к UnicNumber, и у тебя будет генериться вторая цифра подряд.

2024-05-16 17:55 UTC, Rulioff commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
С кратностью 3 не придумал, как исправить.

2024-05-16 17:56 UTC, Rulioff commented on P_38_G.pas
> +      Result := FirstPassword;
Сам не понял, но почему-то работало, хотя не должно.
Исправил.

2024-05-16 17:57 UTC, Rulioff commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Не придумал, как по другому.

2024-05-16 18:10 UTC, Rulioff commented on P_38_G.pas
> +  AllSymbols := '';
Исправил.

2024-05-16 18:11 UTC, Rulioff commented on P_38_G.pas
> +  FirstPassword := '';
Исправил.

2024-05-16 18:11 UTC, Rulioff commented on P_38_G.pas
> +  function GetNumbersLine(): string;
Исправил.

2024-05-16 18:11 UTC, Rulioff commented on P_38_G.pas
> +  function GetCharsLine(): string;
Исправил.

2024-05-16 18:11 UTC, Rulioff commented on P_38_G.pas
> +  function GetCapsCharsLine(): string;
Исправил.

2024-05-16 18:12 UTC, Rulioff commented on P_38_G.pas
> +      Result := ThirdPassword;
Одно, но работало, как за циклом.

2024-05-16 18:14 UTC, Rulioff commented on P_38_G.pas
> +      Result := FourthPassword;
Исправил.

2024-05-16 18:14 UTC, Rulioff commented on P_38_G.pas
> +      end;
Исправил.

2024-05-16 19:18 UTC, dskrasnov commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Думай или спрашивай - будем вместе думать. Но только не текстом.

2024-05-16 19:19 UTC, dskrasnov commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Думай или спрашивай - будем вместе думать. Но только не текстом.

2024-05-17 08:58 UTC, dskrasnov commented on P_38_G.pas
> +      Result := FirstPassword;
Где исправил? Функция отдает значение внутри цикла. Ничего не изменилось.

2024-05-17 17:45 UTC, Rulioff commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Ок.

2024-05-17 17:46 UTC, Rulioff commented on P_38_G.pas
> +        aChars[Random(26)] + aCapsChars[Random(26)];
Ок.

2024-05-19 16:32 UTC, dskrasnov approved these changes

2024-05-19 17:24 UTC, merged