P_38_D faet: Написал 4 булевы функции, которые проверяют условия из задачи P_38_G ввода пользователем пароля
Rulioff/Pascal pull request #50
Opened 2024-05-21 09:29 UTC by Rulioff

![image](https://github.com/Rulioff/Pascal/assets/74359412/4edc0a2e-db19-4412-acbe-fe21dff2a87c)
![image](https://github.com/Rulioff/Pascal/assets/74359412/55b67a5c-b861-4a71-8c1e-01cf2d4ea328)

2024-05-21 09:31 UTC, Rulioff commented
В функции GetNumbers, в строке 26 компилятор ругается на неверный тип. 
![image](https://github.com/Rulioff/Pascal/assets/74359412/ffb20083-9bc6-44c4-ad35-11059cf97c7a)

2024-05-22 20:00 UTC, dskrasnov requested changes

2024-05-22 20:00 UTC, dskrasnov commented on P_38_D.pas
> +    CheckNumbers := 0;
С нейминкгом опять беда. CheckNumbers  - проверить числа или проверочные числа. Что ты имел в виду. Я вижу, что это количество чисел. Ну и назови их адекватно. Что за CheckNumbers?

Остальное по аналогии. Не хочу повторяться. Сам найдешь.

2024-05-22 20:00 UTC, dskrasnov commented on P_38_D.pas
> +    if (CheckNumbers > 1) and (CheckLetters > 1) and (CheckCapsLetters > 1) then
А обязательно ли проходить по всему паролю? Если первые три символа повторяются, надо ли считать остальные чтобы вернуть false?

Там ниже наверняка есть похожие косяки. Сам найди.

2024-05-22 20:00 UTC, dskrasnov commented on P_38_D.pas
> +  function CheckingFirstCondition(Password: string): boolean;
Почему CheckingFirstCondition? Почему не CheckFirstCondition? Аргументируй или исправь.

А вообще,, имена булевых переменных и функций принято начинать с `is`. Т.е. имя должно представлять собой вопрос, на который отвечает значение. Например IsBoxEmpty - коробка пустая? Пофантазируй.

Поищи подобные косяки. Наверняка тут еще есть.

2024-05-22 20:00 UTC, dskrasnov commented on P_38_D.pas
> +        Result := False;
А где true? И ниже то же.

2024-05-22 20:00 UTC, dskrasnov commented on P_38_D.pas
> +  function CheckingFourthCondition(Password: string): boolean;
А нельзя тут использовать существующие функции?

2024-05-23 06:35 UTC, Rulioff commented on P_38_D.pas
> +        Result := False;
По умолчанию будет True, смысл лишний раз писать?

2024-05-23 07:02 UTC, Rulioff commented on P_38_D.pas
> +  function CheckingFourthCondition(Password: string): boolean;
Думаю получится.

2024-05-23 07:47 UTC, dskrasnov commented on P_38_D.pas
> +        Result := False;
Почему? Кто сказал? Где это указано? Что, реально - любая булева функция по умолчанию возвращает true? Что за бред?

2024-05-23 07:48 UTC, dskrasnov commented on P_38_D.pas
> +  function CheckingFourthCondition(Password: string): boolean;
Пробуй.

2024-05-23 09:04 UTC, Rulioff commented on P_38_D.pas
> +  function CheckingFirstCondition(Password: string): boolean;
Использовал вопросительную форму IsFirstConditionCheck.

2024-05-23 15:26 UTC, dskrasnov commented on P_38_D.pas
> +  function CheckingFirstCondition(Password: string): boolean;
И что это значит? По-русски и по-английски.

2024-05-25 15:11 UTC, Rulioff commented on P_38_D.pas
> +    CheckNumbers := 0;
Ты прав, с неймингом бардак, буду над этим работать. Исправил на CountNumbers и дальше по аналогии, так как здесь идёт подсчёт цифр.

2024-05-25 15:12 UTC, Rulioff commented on P_38_D.pas
> +    if (CheckNumbers > 1) and (CheckLetters > 1) and (CheckCapsLetters > 1) then
Исправил, добавил ранний выход.

2024-05-25 15:17 UTC, Rulioff commented on P_38_D.pas
> +  function CheckingFirstCondition(Password: string): boolean;
Это значит - проверка первого условия. Это нам и требуется проверить.

2024-05-25 15:21 UTC, Rulioff commented on P_38_D.pas
> +        Result := False;
Я погорячился. Это у меня на практике в паскале по умолчанию получалось True, нигде в описании такого не встречал. И если не ошибаюсь, то в Java и C++ по умолчанию ноль.

2024-05-25 15:23 UTC, Rulioff commented on P_38_D.pas
> +  function CheckingFourthCondition(Password: string): boolean;
Получилось. Спасибо!

2024-05-25 15:44 UTC, dskrasnov commented on P_38_D.pas
> +    CheckNumbers := 0;
Ну, давай этот твой CountNumbers кинем в Google Переводчик. Что получится? Считать цифры. Понимаешь, в чем проблема? Исправляй. И аналогии тоже.

2024-05-25 16:48 UTC, dskrasnov commented on P_38_D.pas
> +        Result := False;
Не понял. Если... то... иначе вернем false? На каждом шаге цикла? Как это?

2024-05-25 16:48 UTC, dskrasnov commented on P_38_D.pas
> +      else
Зачем эти else?

2024-05-25 16:48 UTC, dskrasnov commented on P_38_D.pas
> +        WriteLn(Password[Index], ': Недопустимый символ');
А эти функции разве должны сообщать о недопустимых функциях?

2024-05-25 16:48 UTC, dskrasnov commented on P_38_D.pas
> +  function CheckingFirstCondition(Password: string): boolean;
Еще раз - имена булевых переменных и функций принято начинать с is (или Does  и прочих вспомогательных глаголов, подходящих по смыслу). Т.е. имя должно представлять собой вопрос, на который отвечает значение. Например IsBoxEmpty - коробка пустая?

Ты говоришь, что твое IsFirstConditionCheck значит - проверка первого условия. Во-первых, это не так - проверь сам в переводчике. Во-вторых, где вопрос во фразе "проверка первого условия"? Еще раз - имя должно представлять собой вопрос, на который отвечает значение. Например IsBoxEmpty - коробка пустая?

А я даже подсказку оставил.

2024-05-25 16:48 UTC, Rulioff commented on P_38_D.pas
> +    CheckNumbers := 0;
Для перевода мы не пользуемся гугл-транслейтом. Наши инструменты:

[multitran.com](http://multitran.com/) для перевода,

[wooordhunt.ru](http://wooordhunt.ru/) для поиска английских терминов в контексте,

[context.reverso.net](http://context.reverso.net/translation/) для поиска терминов по контексту. ![image](https://github.com/Rulioff/Pascal/assets/74359412/a278794d-08a7-4fbc-9c8a-ce2b3a3d82d2)
Использовал этот сайт: https://context.reverso.net/translation/english-russian/Count+Numbers

2024-05-25 16:57 UTC, dskrasnov requested changes

2024-05-25 16:57 UTC, dskrasnov commented on P_38_D.pas
> +        Result := False;
Во-первых, если не ошибаюсь, то в Java и C++, если в сигнатуре указано, что функция должна что-то вернуть, то она должна это вернуть - явно и без умолчаний.

Во-вторых, где ты добавил else true?

2024-05-25 17:12 UTC, dskrasnov commented on P_38_D.pas
> +    CheckNumbers := 0;
Пиздец ты умный. :-) Только "to count numbers" это глагол "считать числа". А тебе нужно "количество чисел", но так чтобы обойтись без "of". Надеюсь, все эти сервисы тебе помогут.

2024-05-25 17:22 UTC, Rulioff commented on P_38_D.pas
> +        WriteLn(Password[Index], ': Недопустимый символ');
Убрал лишнюю проверку.

2024-05-25 17:58 UTC, dskrasnov commented on P_38_D.pas
> +        Result := False;
Во-первых, если не ошибаюсь, то в Java и C++, если в сигнатуре указано, что функция должна что-то вернуть, то она должна это вернуть - явно и без умолчаний.

Во-вторых, где ты добавил else true?

2024-05-25 17:59 UTC, dskrasnov commented on P_38_D.pas
> +  function CheckingFirstCondition(Password: string): boolean;
Еще раз - имена булевых переменных и функций принято начинать с is (или Does и прочих вспомогательных глаголов, подходящих по смыслу). Т.е. имя должно представлять собой вопрос, на который отвечает значение. Например IsBoxEmpty - коробка пустая?

Ты говоришь, что твое IsFirstConditionCheck значит - проверка первого условия. Во-первых, это не так - проверь сам в переводчике. Во-вторых, где вопрос во фразе "проверка первого условия"? Еще раз - имя должно представлять собой вопрос, на который отвечает значение. Например IsBoxEmpty - коробка пустая?

А я даже подсказку оставил.

2024-05-26 14:49 UTC, dskrasnov approved these changes

2024-05-26 14:52 UTC, merged